title: BOMAG Machine Comparison Tool
description: A web-based tool for comparing BOMAG machines with competitors' machines
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass configuration
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore 